In [1]:
print("Tamim Mahmud")

Tamim Mahmud


In [3]:
n=input("Name: ")
print("My name is ",n)

Name:  Kulsom akter Sinthia


My name is  Kulsom akter Sinthia


In [4]:
import numpy as np


In [11]:
a=np.array([1,2,3]) #1-D array or vector 


In [7]:
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

In [10]:
a.ndim


1

In [12]:
b=np.array([[1.0,2,3],[4,5,6]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
type(b)

numpy.ndarray

In [15]:
b.shape

(2, 3)

In [18]:
r=np.array([[[1.0,2.3,3],[4,5,6],[7,8,9]]])

In [21]:
r

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
type(r)

numpy.ndarray

In [24]:
r.shape

(1, 3, 3)

In [25]:
r.ndim

3

In [26]:
a.dtype

dtype('int32')

In [28]:
r.dtype

dtype('int32')

In [29]:
r.dtype

dtype('int32')

In [30]:
r.dtype

dtype('int32')

In [31]:
b.dtype

dtype('int32')

In [32]:
a.size,r.size

(3, 9)

In [34]:
a.nbytes,r.nbytes

(12, 36)

In [35]:
a1=np.array([1,2,3,4,5],dtype="int")

In [36]:
a1

array([1, 2, 3, 4, 5])

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [13]:
a.dtype

dtype('int32')

In [14]:
a.ndim

1

In [9]:
b=np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
b.dtype

dtype('int32')

In [16]:
b.ndim

2

In [17]:
print("tamim mahnmud sinthia orita kulsom shakib al hasan ami -pari cse porte")

tamim mahnmud sinthia orita kulsom shakib al hasan ami -pari cse porte


In [18]:
a=np.array([1,2,3],dtype="int")

In [19]:
a

array([1, 2, 3])

In [22]:
z=np.zeros((2,2,1),dtype="float")

In [24]:
z=np.zeros((2,2,1),dtype="float")

In [25]:
z

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [28]:
s=np.zeros((3,3),dtype="int")

In [27]:
s

array([[0., 0.],
       [0., 0.]])

In [29]:
s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
l=np.zeros((5,5),dtype="int")

In [31]:
l

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
l=np.ones((3,3),dtype="int")

In [33]:
l

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
t=np.full((4,5),10)

In [35]:
t

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [36]:
m=np.identity(5,dtype="int")

In [38]:
m

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [41]:
eye=np.eye(3,3,1)

In [40]:
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [44]:
w=np.arange(1,100,5)

In [45]:
w

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [48]:
l=np.linspace(1,5,100)

In [49]:
l

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [51]:
l.size

100

In [52]:
m=np.linspace(1,100,500,dtype="int")

In [53]:
m

array([  1,   1,   1,   1,   1,   1,   2,   2,   2,   2,   2,   3,   3,
         3,   3,   3,   4,   4,   4,   4,   4,   5,   5,   5,   5,   5,
         6,   6,   6,   6,   6,   7,   7,   7,   7,   7,   8,   8,   8,
         8,   8,   9,   9,   9,   9,   9,  10,  10,  10,  10,  10,  11,
        11,  11,  11,  11,  12,  12,  12,  12,  12,  13,  13,  13,  13,
        13,  14,  14,  14,  14,  14,  15,  15,  15,  15,  15,  16,  16,
        16,  16,  16,  17,  17,  17,  17,  17,  18,  18,  18,  18,  18,
        19,  19,  19,  19,  19,  20,  20,  20,  20,  20,  21,  21,  21,
        21,  21,  22,  22,  22,  22,  22,  23,  23,  23,  23,  23,  24,
        24,  24,  24,  24,  25,  25,  25,  25,  25,  25,  26,  26,  26,
        26,  26,  27,  27,  27,  27,  27,  28,  28,  28,  28,  28,  29,
        29,  29,  29,  29,  30,  30,  30,  30,  30,  31,  31,  31,  31,
        31,  32,  32,  32,  32,  32,  33,  33,  33,  33,  33,  34,  34,
        34,  34,  34,  35,  35,  35,  35,  35,  36,  36,  36,  3

In [54]:
m.size

500

In [56]:
k=np.empty((1,5))

In [57]:
k

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69761995e-312, 1.66400008e-294]])

In [60]:
k

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69761995e-312, 1.66400008e-294]])

In [61]:
a=np.array([1,2,3,4,5])

In [62]:
a

array([1, 2, 3, 4, 5])

In [63]:
print(a)

[1 2 3 4 5]


In [65]:
a[4]

5

In [67]:
a2=np.random.randint(1,10,size=(3,3))

In [68]:
a2

array([[9, 5, 5],
       [2, 3, 3],
       [3, 6, 2]])

In [69]:
a2[0][0] 

9

In [71]:
a2[0][1]

5

In [72]:
a2[1][1]

3

In [73]:
a2[2][2]

2

In [81]:
 s=np.random.randint(1,10,size=(2,3,3))

In [82]:
s

array([[[5, 7, 6],
        [2, 8, 7],
        [7, 8, 3]],

       [[6, 8, 6],
        [8, 4, 3],
        [2, 8, 8]]])

In [80]:
s[1][1]

array([1, 7, 3])

In [83]:
s[1][1]

array([8, 4, 3])

In [84]:
s[0][1][1]

8

In [85]:
s[1][1][1]

4

In [86]:
s[0][2][0]

7

In [87]:
s[1][1][2]

3

In [89]:
s[1,1,2]

3

In [91]:
a=np.array([1,2,3,4,5])

In [92]:
a

array([1, 2, 3, 4, 5])

In [93]:
a[0:4]

array([1, 2, 3, 4])

In [94]:
a[ :3]

array([1, 2, 3])

In [95]:
a[2:]

array([3, 4, 5])

In [96]:
s

array([[[5, 7, 6],
        [2, 8, 7],
        [7, 8, 3]],

       [[6, 8, 6],
        [8, 4, 3],
        [2, 8, 8]]])

In [97]:
a2

array([[9, 5, 5],
       [2, 3, 3],
       [3, 6, 2]])

In [98]:
a2[0:2]

array([[9, 5, 5],
       [2, 3, 3]])

In [99]:
a2[0:2,0:2]

array([[9, 5],
       [2, 3]])

In [100]:
a2[1:3,1:3]

array([[3, 3],
       [6, 2]])

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
a=np.reshape(a,(3,2))

In [7]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a.shape

(3, 2)

#resize

In [11]:
a=np.resize(a,(3,3))

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [14]:
a=np.reshape(a,(3,3))

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [16]:
a=np.resize(a,(4,3))

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3]])

In [18]:
a=np.reshape(a,(3,4))

In [19]:
a

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 1, 2, 3]])

In [20]:
a=np.resize(a,(5,4))

In [21]:
a

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 4],
       [5, 6, 1, 2]])

In [23]:
a=np.reshape(a,(4,5))

In [24]:
a

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 1],
       [2, 3, 1, 2, 3],
       [4, 5, 6, 1, 2]])

#ravel

In [26]:
a=np.random.randint(1,10,(2,3))

In [27]:
a

array([[8, 5, 3],
       [6, 8, 2]])

In [28]:
a=np.ravel(a)

In [29]:
a

array([8, 5, 3, 6, 8, 2])

In [30]:
a.shape

(6,)

In [31]:
a

array([8, 5, 3, 6, 8, 2])

In [32]:
a=np.random.randint(1,20,(3,4))

In [33]:
a

array([[ 5,  8, 18,  6],
       [11,  2, 12, 19],
       [19,  6, 14, 10]])

In [37]:
s=a.flatten()

In [36]:
s

<function ndarray.flatten>

In [38]:
s

array([ 5,  8, 18,  6, 11,  2, 12, 19, 19,  6, 14, 10])

In [39]:
a[0]=99

In [40]:
a

array([[99, 99, 99, 99],
       [11,  2, 12, 19],
       [19,  6, 14, 10]])

In [41]:
print(a)

[[99 99 99 99]
 [11  2 12 19]
 [19  6 14 10]]


In [42]:
a=np.random.randint(1,20,(4,5))

In [43]:
a

array([[ 1,  1,  4, 14,  3],
       [10,  7, 19,  9, 10],
       [ 5,  4,  8,  2,  9],
       [14, 10,  6, 19,  4]])

In [44]:
a.ravel()

array([ 1,  1,  4, 14,  3, 10,  7, 19,  9, 10,  5,  4,  8,  2,  9, 14, 10,
        6, 19,  4])

In [48]:
a[0]=123

In [49]:
a

array([[123, 123, 123, 123, 123],
       [ 10,   7,  19,   9,  10],
       [  5,   4,   8,   2,   9],
       [ 14,  10,   6,  19,   4]])

In [50]:
a.flatten()

array([123, 123, 123, 123, 123,  10,   7,  19,   9,  10,   5,   4,   8,
         2,   9,  14,  10,   6,  19,   4])

In [51]:
a[0]=333

In [52]:
a

array([[333, 333, 333, 333, 333],
       [ 10,   7,  19,   9,  10],
       [  5,   4,   8,   2,   9],
       [ 14,  10,   6,  19,   4]])

In [53]:
p=a.flatten()

In [54]:
p

array([333, 333, 333, 333, 333,  10,   7,  19,   9,  10,   5,   4,   8,
         2,   9,  14,  10,   6,  19,   4])

In [55]:
a

array([[333, 333, 333, 333, 333],
       [ 10,   7,  19,   9,  10],
       [  5,   4,   8,   2,   9],
       [ 14,  10,   6,  19,   4]])

In [57]:
k=np.random.randint(1,10,(2,3))

In [58]:
w=a.flatten()

In [59]:
w

array([333, 333, 333, 333, 333,  10,   7,  19,   9,  10,   5,   4,   8,
         2,   9,  14,  10,   6,  19,   4])

In [60]:
a[0]=0

In [61]:
w

array([333, 333, 333, 333, 333,  10,   7,  19,   9,  10,   5,   4,   8,
         2,   9,  14,  10,   6,  19,   4])

In [62]:
k[0]=999

In [63]:
w

array([333, 333, 333, 333, 333,  10,   7,  19,   9,  10,   5,   4,   8,
         2,   9,  14,  10,   6,  19,   4])

In [64]:
k

array([[999, 999, 999],
       [  7,   4,   8]])

In [65]:
k.flatten()

array([999, 999, 999,   7,   4,   8])

In [66]:
k[0]=888

In [67]:
k

array([[888, 888, 888],
       [  7,   4,   8]])

In [68]:
l=k.flatten()

In [69]:
l

array([888, 888, 888,   7,   4,   8])

In [70]:
k

array([[888, 888, 888],
       [  7,   4,   8]])

In [71]:
d=np.random.randint(1,10,(2,3))

In [72]:
d

array([[2, 8, 7],
       [8, 3, 5]])

In [73]:
h=np.ravel(d)

In [74]:
h

array([2, 8, 7, 8, 3, 5])

In [75]:
d[0]=0

In [76]:
h

array([0, 0, 0, 8, 3, 5])

In [77]:
d

array([[0, 0, 0],
       [8, 3, 5]])

In [79]:
q=d.flatten()

In [80]:
q

array([0, 0, 0, 8, 3, 5])

In [81]:
d[0]=88888

In [82]:
q

array([0, 0, 0, 8, 3, 5])

In [83]:
f=np.random.randint(1,10,(2,3))

In [84]:
f

array([[8, 6, 7],
       [9, 8, 7]])

In [85]:
ss=f.flatten()

In [86]:
ss

array([8, 6, 7, 9, 8, 7])

In [87]:
f[0]=0

In [88]:
ss

array([8, 6, 7, 9, 8, 7])

In [89]:
f[0]=99

In [90]:
ss

array([8, 6, 7, 9, 8, 7])

In [91]:
ss[0]=999

In [92]:
ss

array([999,   6,   7,   9,   8,   7])

In [93]:
f

array([[99, 99, 99],
       [ 9,  8,  7]])

#defining array shape

In [94]:
f

array([[99, 99, 99],
       [ 9,  8,  7]])

In [95]:
f.shape

(2, 3)

In [96]:
f.shape=(3,2)

In [97]:
f

array([[99, 99],
       [99,  9],
       [ 8,  7]])

In [98]:
x=np.arange(1,10).reshape(3,3)

In [99]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
y=2*x

In [101]:
y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [103]:
np.hstack((x,y))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [104]:
np.column_stack((x,y))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [109]:
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [110]:
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [112]:
np.row_stack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [113]:
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [114]:
np.dstack((x,y))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

In [115]:
ar=np.array([1,2,3,4,5])

In [116]:
ar

array([1, 2, 3, 4, 5])

In [117]:
ss=np.mean(ar)

In [118]:
ss

3.0

In [119]:
a=np.array([1,2,3,4,5,6])

In [120]:
a

array([1, 2, 3, 4, 5, 6])

In [121]:
np.mean(a)

3.5

In [122]:
np.sum(a)

21

In [123]:
np.std(a)

1.707825127659933

In [124]:
np.median(a)

3.5

In [125]:
np.std(a)

1.707825127659933

In [126]:
np.min(a)

1

In [127]:
np.max(a)

6

In [128]:
np.argmin(a)

0

In [129]:
np.argmax(a)

5

In [131]:
a=np.array([[1,2,3],[4,5,6]])

In [132]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
np.sum(a,axis=0)

array([5, 7, 9])

In [134]:
np.sum(a,axis=1)

array([ 6, 15])

In [136]:
ass=np.array([2,4,6,8])

In [137]:
ass

array([2, 4, 6, 8])

In [139]:
np.mean(ass)

5.0

In [140]:
np.var(ass)

5.0

In [141]:
np.std(ass)

2.23606797749979

In [142]:
ad=np.array([1,2,3,4,5])


In [143]:
ad+10

array([11, 12, 13, 14, 15])

In [144]:
ad*5

array([ 5, 10, 15, 20, 25])

In [145]:
dd=np.random.randint(1,10,(2,3))

In [146]:
dd

array([[6, 5, 1],
       [1, 3, 4]])

In [147]:
df=dd*2

In [148]:
df

array([[12, 10,  2],
       [ 2,  6,  8]])

In [150]:
dd.shape=(3,2)

In [151]:
dd

array([[6, 5],
       [1, 1],
       [3, 4]])

In [152]:
ds=dd*2

In [153]:
ds

array([[12, 10],
       [ 2,  2],
       [ 6,  8]])

In [155]:
a=np.arange(1,10)

In [156]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a=np.random.randint(1,10,(2,2))

In [158]:
a

array([[5, 8],
       [1, 4]])

In [159]:
b=np.random.randint(3,9,(2,2))

In [160]:
b

array([[5, 6],
       [5, 5]])

In [161]:
np.dot(a,b)

array([[65, 70],
       [25, 26]])

In [163]:
z=np.array([[1,3],[5,7]])

In [164]:
z

array([[1, 3],
       [5, 7]])

In [165]:
np.linalg.inv(a)

array([[ 0.33333333, -0.66666667],
       [-0.08333333,  0.41666667]])

In [166]:
m=np.linalg.inv(a)

In [167]:
m

array([[ 0.33333333, -0.66666667],
       [-0.08333333,  0.41666667]])

In [168]:
A = np.array([[1, 3], [5, 7]])


In [169]:
A

array([[1, 3],
       [5, 7]])

In [170]:
inv_A = np.linalg.inv(A)

In [171]:
print(inv_A)


[[-0.875  0.375]
 [ 0.625 -0.125]]


In [172]:
inv_A

array([[-0.875,  0.375],
       [ 0.625, -0.125]])

In [173]:
a=np.array([[1,3],[5,7]])

In [174]:
a

array([[1, 3],
       [5, 7]])

In [175]:
np.linalg.inv(a)

array([[-0.875,  0.375],
       [ 0.625, -0.125]])

In [176]:
p=np.array([[2,0],[0,3]])

In [177]:
p

array([[2, 0],
       [0, 3]])

In [178]:
f,g=np.linalg.eig(p)

In [179]:
f

array([2., 3.])

In [180]:
g

array([[1., 0.],
       [0., 1.]])

In [181]:
print(f)

[2. 3.]


In [182]:
print(g)

[[1. 0.]
 [0. 1.]]


In [183]:
m=np.arange(1,10)

In [184]:
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
v=np.random.randint(1,23,(2,3))

In [187]:
v

array([[12, 19, 17],
       [ 3,  3,  5]])

In [188]:
np.transpose(v)

array([[12,  3],
       [19,  3],
       [17,  5]])

In [190]:
l=np.random.randint(1,28,(3,3))

In [191]:
l

array([[15, 19, 10],
       [ 1, 21, 19],
       [ 4,  8,  2]])

In [192]:
np.linalg.det(l)

-1003.9999999999998

In [193]:
m=l*2

In [194]:
m

array([[30, 38, 20],
       [ 2, 42, 38],
       [ 8, 16,  4]])

In [195]:
l @m

array([[ 568, 1528, 1062],
       [ 224, 1224,  894],
       [ 152,  520,  392]])

In [196]:
np.random.rand(3)

array([0.21776078, 0.65794655, 0.28575109])

In [197]:
np.random.rand(2,2)

array([[0.67781659, 0.03735377],
       [0.62935789, 0.06969861]])

In [198]:
np.random.randn(3)

array([ 0.192382  , -0.41889406,  0.26465659])

In [199]:
b=np.random.randn(3)

In [200]:
b

array([ 2.24393894, -1.3283158 ,  0.71977254])

In [201]:
np.mean(b)

0.5451318909767574

In [202]:
np.std(b)

1.4635858929891252

In [206]:
np.random.seed(6)

In [207]:
print(np.random.rand(3))

[0.89286015 0.33197981 0.82122912]


In [208]:
print(np.random.rand(10))

[0.04169663 0.10765668 0.59505206 0.52981736 0.41880743 0.33540785
 0.62251943 0.43814143 0.73588211 0.51803641]


In [209]:
np.random.seed(9)

In [210]:
print(np.random.rand(3))

[0.01037415 0.50187459 0.49577329]


In [211]:
np.random.seed(0)

In [212]:
print(np.random.rand(3))

[0.5488135  0.71518937 0.60276338]


In [213]:
print(np.random.rand(3))

[0.54488318 0.4236548  0.64589411]


In [214]:
arr = np.array([10, 15, 20, 25, 30])

In [215]:
arr

array([10, 15, 20, 25, 30])

In [216]:
m=arr>20

In [217]:
m

array([False, False, False,  True,  True])

In [218]:
arr[m]

array([25, 30])

In [219]:
x=arr[arr%2==0]

In [220]:
x

array([10, 20, 30])

In [221]:
l=arr[(arr>=10)&(arr<=20)]

In [222]:
l

array([10, 15, 20])

In [223]:
l=a[(a<10)|(a>20)]

In [224]:
l

array([1, 3, 5, 7])

In [225]:
a=np.array([5,10,15,20,25])

In [226]:
a

array([ 5, 10, 15, 20, 25])

In [227]:
l=a[(a<10)|(a>20)]

In [228]:
l

array([ 5, 25])

In [229]:
a[a>15]=999

In [230]:
a

array([  5,  10,  15, 999, 999])

In [231]:
data = np.array([1, 2, np.nan, 4, 5])

In [232]:
data

array([ 1.,  2., nan,  4.,  5.])

In [233]:
np.isnan(data)

array([False, False,  True, False, False])